const CONFIRM_COLLATERAL_CHOICE = '1-confirm-collateral-choice';
const CHANGE_COLLATERAL_CHOICE = '1A-change-collateral-choice';

const CONFIRM_COLLATERAL_CHOICE_NUM = 1;
const CHANGE_COLLATERAL_CHOICE_NUM = 2;

const stepNames = {
  [CONFIRM_COLLATERAL_CHOICE]: CONFIRM_COLLATERAL_CHOICE_NUM,
  [CHANGE_COLLATERAL_CHOICE]: CHANGE_COLLATERAL_CHOICE_NUM
};

export {
    CONFIRM_COLLATERAL_CHOICE,
    CHANGE_COLLATERAL_CHOICE,
    CONFIRM_COLLATERAL_CHOICE_NUM,
    CHANGE_COLLATERAL_CHOICE_NUM
}

export default stepNames;