const CONFIRM_COLLATERAL_CHOICE = '1-confirm-collateral-choice';
const CHANGE_COLLATERAL_CHOICE = '2-change-collateral-choice';
const LOCK_COLLATERAL_CHOICE = '3-lock-collateral-choice';
const DRAW_DAI_CHOICE = '4-draw-dai-choice';
const CONFIRM_VAULT_CHOICE = '5-confirm-vault';
const OPEN_VAULT_CHOICE = '6-open-vault';

const CONFIRM_COLLATERAL_NUM = 1;
const CHANGE_COLLATERAL_NUM = 2;
const LOCK_COLLATERAL_NUM = 3;
const DRAW_DAI_NUM = 4;
const CONFIRM_VAULT_NUM = 5;
const OPEN_VAULT_NUM = 6;

const stepNames = {
  [CONFIRM_COLLATERAL_CHOICE]: CONFIRM_COLLATERAL_NUM,
  [CHANGE_COLLATERAL_CHOICE]: CHANGE_COLLATERAL_NUM,
  [LOCK_COLLATERAL_CHOICE]: LOCK_COLLATERAL_NUM,
  [DRAW_DAI_CHOICE]: DRAW_DAI_NUM,
  [CONFIRM_VAULT_CHOICE]: CONFIRM_VAULT_NUM,
  [OPEN_VAULT_CHOICE]: OPEN_VAULT_NUM
};

export {
    CONFIRM_COLLATERAL_CHOICE,
    CHANGE_COLLATERAL_CHOICE,
    LOCK_COLLATERAL_CHOICE,
    DRAW_DAI_CHOICE,
    CONFIRM_VAULT_CHOICE,
    OPEN_VAULT_CHOICE,
    CONFIRM_COLLATERAL_NUM,
    CHANGE_COLLATERAL_NUM,
    LOCK_COLLATERAL_NUM,
    DRAW_DAI_NUM,
    CONFIRM_VAULT_NUM,
    OPEN_VAULT_NUM
}

export default stepNames;